 /* 🟢 Question 1 — Revenue by Category

The finance team wants to know the total revenue generated by each product category.

Display:

Product_Category
Total_Revenue

Sort by highest revenue.
*/

SELECT product_category,
		sum(total_price) as revenue
	  -- sum(total_price) as total_revenue
FROM Shop_data
GROUP BY product_category
ORDER BY Revenue DESC;


/*🟢 Question 2 — Average Rating by Brand

The quality team wants to know the average customer rating for every brand.

Display:

Brand
Average_Rating

Round to 2 decimal places.

Sort by highest rating.
*/
SELECT Brand,

	   ROUND(AVG(Rating),2) as Average_rating
FROM shop_data
GROUP BY brand
ORDER BY Average_rating DESC;

/*
🟢 Question 3 — Category Revenue Report
📖 Business Problem

The Finance Department wants to know how much revenue each product category generated from successfully delivered orders.

Display  :  Product_Category
			Total_Orders
			Total_Revenue
			
			
			Conditions
			Include only Delivered orders.
			Ignore rows where Total_Price is NULL.
			Sort by Total_Revenue (highest first).*/--
SELECT product_category,	 
	  
	   COUNT(*) AS total_quantity,
	   sum(total_price) as total_revenue
FROM shop_data
WHERE delivery_status = 'Delivered'
	  AND total_price is not null
GROUP BY product_category
ORDER BY total_revenue DESC;

/*
.
🟢 Question 4 — Brand Performance Dashboard
📖 Business Problem

The Product Head wants to evaluate brand performance for premium products.

Display:    Brand (Trimmed)
			Total_Products_Sold
			Highest_Unit_Price
			Lowest_Unit_Price
			Average_Rating
			Conditions
			Product_Category = Electronics
			Unit_Price > 1000
			Rating IS NOT NULL

Sort by:

Average_Rating DESC

*/
SELECT 
	  TRIM(Brand),
	  max(unit_price),
	  COUNT(*),
	  MIN(unit_price),
	  AVG(rating) as average_rating

from shop_data
WHERE  product_category = 'Electronics'
	   AND Unit_price >1000
	   AND rating is not null
GROUP BY Brand 
ORDER BY AVERAGE_RATING DESC;
	   
/*
🟢 Question 5 — Payment Mode Analysis
📖 Business Problem

The Finance Team wants to understand customer payment behavior.

Display :   Payment_Mode
			Total_Transactions
			Total_Revenue
			
			Conditions
			Total_Price > 500
			Delivery_Status is NOT Cancelled

Sort by:

Total_Transactions DESC
	*/   
SELECT   payment_mode,
	     count(*) AS total_transaction,
		 sum(total_price) 
FROM shop_datA
WHERE total_price>500
	  AND  delivery_status <> 'Cancelled'
GROUP BY  payment_mode 
ORDER BY total_transaction;

/*
                   🟢 Question 1 — Product Quality Report
📖 Business Problem

The Quality Assurance Team wants to monitor customer ratings for each product.

👉 One row should represent one Product.

Display :  Product_Name
			Total_Reviews
			Average_Rating
			Highest_Rating
			Lowest_Rating
Conditions :
Rating IS NOT NULL
Delivery_Status = 'Delivered'

Sort By
Average_Rating DESC
✅ Solution
*/
SELECT
    product_name,
    COUNT(rating) AS total_reviews,
    ROUND(AVG(rating), 2) AS average_rating,
    MAX(rating) AS highest_rating,
    MIN(rating) AS lowest_rating
FROM shop_data
WHERE rating IS NOT NULL
  AND delivery_status = 'Delivered'
GROUP BY product_name
ORDER BY average_rating DESC;

            /*🟢 Question 2 — City Performance Report
📖 Business Problem

The Business Intelligence Team wants to compare sales performance across different cities.

👉 One row should represent one City.

Display :   City
			Total_Orders
			Total_Revenue
			Average_Order_Value
Conditions
Product_Category IN ('Electronics', 'Fashion', 'Furniture')
Delivery_Status = 'Delivered'
Total_Price > 2000

Sort By
Total_Revenue DESC
✅ Solution
*/
SELECT
    city,
    COUNT(*) AS total_orders,
    SUM(total_price) AS total_revenue,
    ROUND(AVG(total_price), 2) AS average_order_value
FROM shop_data
WHERE product_category IN ('Electronics', 'Fashion', 'Furniture')
  AND delivery_status = 'Delivered'
  AND total_price > 2000
GROUP BY city
ORDER BY total_revenue DESC;


            /*🟢 Question 3 — Payment Mode Analysis
📖 Business Problem

The Finance Team wants to compare customer purchasing behavior based on their preferred payment method.
👉 One row should represent one Payment_Mode.
Display  :Payment_Mode
		Total_Revenue
		Average_Order_Value
		Highest_Order
		Lowest_Order
		Conditions
		Delivery_Status = 'Delivered'
		Rating >= 4
		Total_Price IS NOT NULL
Sort By
Total_Revenue DESC
Average_Order_Value DESC
✅ Solution
*/
SELECT
    payment_mode,
    SUM(total_price) AS total_revenue,
    ROUND(AVG(total_price), 2) AS average_order_value,
    MAX(total_price) AS highest_order,
    MIN(total_price) AS lowest_order
FROM shop_data
WHERE delivery_status = 'Delivered'
  AND rating >= 4
  AND total_price IS NOT NULL
GROUP BY payment_mode
ORDER BY total_revenue DESC,
         average_order_value DESC;

		 
 /*                     🟢 Question 4 — Executive Sales Audit (Boss Challenge)
📖 Business Problem
You are working as a Data Analyst at Amazon.
The CEO wants a report showing the sales performance of every Product Category.
👉 One row should represent one Product_Category.

Display : Product_Category
		Total_Orders
		Total_Revenue
		Average_Order_Value
		Highest_Order
		Lowest_Order
		Revenue_Level
		Revenue_Level Rules (CASE)
		Total_Revenue ≥ 100000 → Excellent
		Total_Revenue between 50000 and 99999.99 → Good
		Total_Revenue between 20000 and 49999.99 → Average
		Otherwise → Low
		
Conditions
		Delivery_Status = 'Delivered'
		Email ends with @gmail.com
		Rating >= 4
		Phone number has exactly 10 digits
		Transaction month is July, August, September, October, November, or December
		Product_Category IN ('Electronics', 'Fashion', 'Furniture')
		Total_Price IS NOT NULL

Sort By
Total_Revenue DESC
Average_Order_Value DESC
Product_Category ASC
✅ Solution
*/
SELECT
    product_category,
    COUNT(*) AS total_orders,
    SUM(total_price) AS total_revenue,
    ROUND(AVG(total_price), 2) AS average_order_value,
    MAX(total_price) AS highest_order,
    MIN(total_price) AS lowest_order,
    CASE
        WHEN SUM(total_price) >= 100000 THEN 'Excellent'
        WHEN SUM(total_price) BETWEEN 50000 AND 99999.99 THEN 'Good'
        WHEN SUM(total_price) BETWEEN 20000 AND 49999.99 THEN 'Average'
        ELSE 'Low'
    END AS revenue_level
FROM shop_data
WHERE delivery_status = 'Delivered'
  AND email LIKE '%@gmail.com'
  AND rating >= 4
  AND LENGTH(phone_number) = 10
  AND EXTRACT(MONTH FROM transaction_date) BETWEEN 7 AND 12
  AND product_category IN ('Electronics', 'Fashion', 'Furniture')
  AND total_price IS NOT NULL
GROUP BY product_category
ORDER BY total_revenue DESC,
         average_order_value DESC,
         product_category ASC;
		 