
CREATE  TABLE shop_data (
	transaction_id	VARCHAR(300)	,	
	Transaction_Date	DATE,		
	Customer_ID	VARCHAR(300) PRIMARY KEY,
	Customer_Name	VARCHAR(300) NOT NULL,
	Gender	VARCHAR(10),		
	Email	VARCHAR(100) UNIQUE,
	Phone_Number VARCHAR(50) UNIQUE,
	State	VARCHAR(50),	
	City	VARCHAR(50),	
	Product_Category	VARCHAR(50),	
	Product_Name	VARCHAR(50)	,
	Brand	VARCHAR(50)	,	
	Unit_Price	NUMERIC(15,2),	
	Quantity	INTEGER	,	
	Total_Price	NUMERIC(50,2),	
	Payment_Mode	VARCHAR(50),	
	Delivery_Status	VARCHAR(50),	
	Customer_Type	VARCHAR(50),	
	Rating	NUMERIC(3,1)		

);

SELECT * FROM shop_data;

SELECT  length(customer_name) AS UPPER from shop_data ;

/*
Q1. Total Sales

The finance team wants to know the total revenue generated from all completed deliveries.

Output:

Total Revenue
*/

SELECT 
	   sum(total_price) from shop_data
 	WHERE delivery_status = 'Delivered';

/*
2. Premium Products

The product team wants to know the highest unit price among all products.


Output:

Maximum Unit Price
*/
SELECT product_category,
	   product_name,
	   unit_price
FROM shop_data ORDER BY unit_price  desc
LIMIT 1;


/*
3. Customer Rating

The quality team wants to know the average rating received for delivered orders.

Output:

Average Rating
*/
SELECT ROUND(AVG(rating),2) as average_rating 
FROM shop_data
	WHERE  Delivery_Status = 'Delivered';

/*
4. Electronics Revenue

Find the total revenue generated from the Electronics category.

Output:

Total Revenue
*/
SELECT  ROUND(SUM(total_price),2) AS total_revenue from shop_data
	WHERE Product_category = 'Electronics';

/*
5.Product Name Analysis

Display:

Product_Name
Product_Name in uppercase
Product_Name in uppercase
Length of Product_Name
*/

SELECT product_name,
	   UPPER(product_name) AS product_name,
	   LOWER(product_name) AS product_lower,
	  	   LENGTH(product_name) AS product_length
FROM shop_data;

/*
6. Brand Prefix

Display:

Brand
First 3 characters of Brand
*/
SELECT brand,left(brand,3) as left_brand
	 FROM shop_data;



/*
7. Phone Number Check

The customer support team wants to identify customers whose phone number is not exactly 10 characters.

Display:

Customer_Name
Phone_Number
Length of Phone_Number
*/
SELECT customer_name,
	   phone_number,
	   LENGth(phone_number) AS phone_len
	   from shop_data
WHERE NOT LENGTH(phone_number) = 10;



/*
8. Brand Name Cleanup

Some brand names contain extra spaces.

Display:

Original Brand
Trimmed Brand

Use TRIM().
*/
SELECT brand,
	   trim(brand) as space_removed
FROM shop_data;


/*
🔥 Bonus Challenge (Mix of Aggregate + String)

The CEO asks:

Find the total revenue generated by customers whose email ends with gmail.com.

Output:


Total Revenue
*/
SELECT SUM(TOTAL_PRICE) FROM shop_data
	
WHERE email like '%@gmail.com';


/*
=============================🔥 New Mixed Real-World Company Problem==============================

Imagine you're working as a Data Analyst at Amazon. The marketing manager asks:
"We are launching a campaign for premium Gmail customers who purchased electronics and received their orders successfully. Prepare a customer list."

Requirements:
Display:

Customer_Name, Product_Name in UPPERCASE, Brand with extra spaces removed, Email in lowercase
Phone number length
Total_Price

Conditions:

Only Electronics products
Delivery status = 'Delivered'
Email ends with gmail.com
Phone number must be exactly 10 characters
Total_Price greater than 1000

Finally, sort the results by Total_Price in descending order.

*/
SELECT   Customer_Name,
		UPPER(Product_Name) AS  UPPERCASE,
		TRIM(Brand) AS spaces_removed,
		LOWER(Email) AS EMAIL_lowercase,
		phone_number,
		Total_Price
FROM shop_data
WHERE product_category = 'Electronics'
	  AND Delivery_Status = 'Delivered'
	  AND email like  '%@gmail.com'
	  AND LENGTH(phone_number) = 10
	  AND total_price >1000;
	  

 
--=========================date,conditional function 
/*🟢 SQL Practice Set (10 Real Company Problems)
Question 1 – Customer Birthday Offer 🎂

The marketing team wants to send birthday offers to customers who made purchases in January.

Display:

Customer_Name
Email
Transaction_Date

Only include customers whose transaction month is January.

Sort the results by Transaction_Date (oldest first).
*/
SELECT customer_name,
	   email,
	   transaction_date
FROM shop_data
WHERE transaction_date BETWEEN '2024-01-01' AND '2024-01-31'
ORDER BY transaction_date asc;

/*
Question 2 – High Value Female Customers 💳

The sales manager wants a list of female customers who:

spent more than 3000
successfully received their orders

Display:

Customer_Name
Product_Name
Total_Price
Delivery_Status

Sort by Total_Price from highest to lowest.
*/
SELECT customer_name,
	   product_name,
	   Total_price,
	   gender,
	   delivery_status
FROM shop_data
WHERE gender = 'Female' AND total_price >3000 AND delivery_status = 'Delivered'
ORDER BY total_price DESC;



/*
Question 3 – Product Price Classification 🏷️ (CASE WHEN)

The pricing team wants every product to be classified.

Display:

Product_Name
Unit_Price
Price_Category

Rules:

Below 500 → Budget
500–2000 → Standard
Above 2000 → Premium
*/
SELECT product_name,
       Unit_price,
	   
	 CASE 
	 	WHEN total_price <500 then 'Budget'
		WHEN total_price BETWEEN 500 AND 2000 then 'Standard'
		else 'Premium'
	end AS price_category
	FROM shop_data;


/*Question 4 – Weekend Delivery Review 📅

The logistics department wants to review all orders placed on Saturday or Sunday.

Display:

Transaction_ID
Customer_Name
Transaction_Date
Delivery_Status

Sort by Transaction_Date.*/
SELECT customer_name,
	   transaction_date,
	   delivery_status
FROM shop_data
WHERE TO_CHAR(Transaction_date,'')



SELECT TO_CHAR(Transaction_date,'Day') from shop_data;




	   